/**
 * Pydio API V2
 * Access to a Pydio Server. Second version of the API.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AdminWorkspaceInfo model module.
* @module model/AdminWorkspaceInfo
* @version 2.0.0
*/
export default class AdminWorkspaceInfo {
    /**
    * Constructs a new <code>AdminWorkspaceInfo</code>.
    * additional informations provided by the server
    * @alias module:model/AdminWorkspaceInfo
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AdminWorkspaceInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AdminWorkspaceInfo} obj Optional instance to populate.
    * @return {module:model/AdminWorkspaceInfo} The populated <code>AdminWorkspaceInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AdminWorkspaceInfo();

            
            
            

            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'Number');
            }
            if (data.hasOwnProperty('shares')) {
                obj['shares'] = ApiClient.convertToType(data['shares'], 'Number');
            }
        }
        return obj;
    }

    /**
    * computed number of users accessing this workspace
    * @member {Number} user
    */
    user = undefined;
    /**
    * number of children shared from this workspace
    * @member {Number} shares
    */
    shares = undefined;








}


