/**
 * Pydio API V2
 * Access to a Pydio Server. Second version of the API.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The BgAction model module.
* @module model/BgAction
* @version 2.0.0
*/
export default class BgAction {
    /**
    * Constructs a new <code>BgAction</code>.
    * triggers a background action on the client side
    * @alias module:model/BgAction
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>BgAction</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BgAction} obj Optional instance to populate.
    * @return {module:model/BgAction} The populated <code>BgAction</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BgAction();

            
            
            

            if (data.hasOwnProperty('actionName')) {
                obj['actionName'] = ApiClient.convertToType(data['actionName'], 'String');
            }
            if (data.hasOwnProperty('delay')) {
                obj['delay'] = ApiClient.convertToType(data['delay'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} actionName
    */
    actionName = undefined;
    /**
    * @member {Number} delay
    */
    delay = undefined;








}


