/**
 * Pydio API V2
 * Access to a Pydio Server. Second version of the API.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Node from './Node';





/**
* The InlineResponse2001 model module.
* @module model/InlineResponse2001
* @version 2.0.0
*/
export default class InlineResponse2001 {
    /**
    * Constructs a new <code>InlineResponse2001</code>.
    * @alias module:model/InlineResponse2001
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>InlineResponse2001</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2001} obj Optional instance to populate.
    * @return {module:model/InlineResponse2001} The populated <code>InlineResponse2001</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2001();

            
            
            

            if (data.hasOwnProperty('seq_id')) {
                obj['seq_id'] = ApiClient.convertToType(data['seq_id'], 'Number');
            }
            if (data.hasOwnProperty('node')) {
                obj['node'] = Node.constructFromObject(data['node']);
            }
        }
        return obj;
    }

    /**
    * @member {Number} seq_id
    */
    seq_id = undefined;
    /**
    * @member {module:model/Node} node
    */
    node = undefined;








}


