/**
 * Pydio API V2
 * Access to a Pydio Server. Second version of the API.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The MetaSourceParameters model module.
* @module model/MetaSourceParameters
* @version 2.0.0
*/
export default class MetaSourceParameters {
    /**
    * Constructs a new <code>MetaSourceParameters</code>.
    * A set of parameters for meta sources
    * @alias module:model/MetaSourceParameters
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>MetaSourceParameters</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MetaSourceParameters} obj Optional instance to populate.
    * @return {module:model/MetaSourceParameters} The populated <code>MetaSourceParameters</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaSourceParameters();

            
            
            

        }
        return obj;
    }









}


