/**
 * Pydio API V2
 * Access to a Pydio Server. Second version of the API.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import NodeListData from './NodeListData';
import PaginationData from './PaginationData';





/**
* The NodeList model module.
* @module model/NodeList
* @version 2.0.0
*/
export default class NodeList {
    /**
    * Constructs a new <code>NodeList</code>.
    * List of Node objects
    * @alias module:model/NodeList
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>NodeList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NodeList} obj Optional instance to populate.
    * @return {module:model/NodeList} The populated <code>NodeList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NodeList();

            
            
            

            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = PaginationData.constructFromObject(data['pagination']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = NodeListData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/PaginationData} pagination
    */
    pagination = undefined;
    /**
    * @member {module:model/NodeListData} data
    */
    data = undefined;








}


