/**
 * Pydio API V2
 * Access to a Pydio Server. Second version of the API.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PaginationData model module.
* @module model/PaginationData
* @version 2.0.0
*/
export default class PaginationData {
    /**
    * Constructs a new <code>PaginationData</code>.
    * Additional metadata attached to a NodeList for pagination. Could be sent through headers instead.
    * @alias module:model/PaginationData
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PaginationData</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaginationData} obj Optional instance to populate.
    * @return {module:model/PaginationData} The populated <code>PaginationData</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginationData();

            
            
            

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('current')) {
                obj['current'] = ApiClient.convertToType(data['current'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('dirs')) {
                obj['dirs'] = ApiClient.convertToType(data['dirs'], 'Number');
            }
            if (data.hasOwnProperty('remoteSort')) {
                obj['remoteSort'] = ApiClient.convertToType(data['remoteSort'], Object);
            }
        }
        return obj;
    }

    /**
    * total number of children
    * @member {Number} count
    */
    count = undefined;
    /**
    * current page
    * @member {Number} current
    */
    current = undefined;
    /**
    * total number of pages
    * @member {Number} total
    */
    total = undefined;
    /**
    * total number of \"collection\" childrens
    * @member {Number} dirs
    */
    dirs = undefined;
    /**
    * additional attributes describing current server-side sorting
    * @member {Object} remoteSort
    */
    remoteSort = undefined;








}


