/**
 * Pydio API V2
 * Access to a Pydio Server. Second version of the API.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import BgAction from './BgAction';
import NodesDiff from './NodesDiff';
import Task from './Task';





/**
* The PydioResponse model module.
* @module model/PydioResponse
* @version 2.0.0
*/
export default class PydioResponse {
    /**
    * Constructs a new <code>PydioResponse</code>.
    * Generic container for messages after successful operations or errors
    * @alias module:model/PydioResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PydioResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PydioResponse} obj Optional instance to populate.
    * @return {module:model/PydioResponse} The populated <code>PydioResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PydioResponse();

            
            
            

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'String');
            }
            if (data.hasOwnProperty('errorCode')) {
                obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'Number');
            }
            if (data.hasOwnProperty('nodesDiff')) {
                obj['nodesDiff'] = NodesDiff.constructFromObject(data['nodesDiff']);
            }
            if (data.hasOwnProperty('bgAction')) {
                obj['bgAction'] = BgAction.constructFromObject(data['bgAction']);
            }
            if (data.hasOwnProperty('tasks')) {
                obj['tasks'] = ApiClient.convertToType(data['tasks'], [Task]);
            }
        }
        return obj;
    }

    /**
    * @member {String} message
    */
    message = undefined;
    /**
    * @member {String} level
    */
    level = undefined;
    /**
    * @member {Number} errorCode
    */
    errorCode = undefined;
    /**
    * @member {module:model/NodesDiff} nodesDiff
    */
    nodesDiff = undefined;
    /**
    * @member {module:model/BgAction} bgAction
    */
    bgAction = undefined;
    /**
    * @member {Array.<module:model/Task>} tasks
    */
    tasks = undefined;








}


