/**
 * Pydio API V2
 * Access to a Pydio Server. Second version of the API.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Role model module.
* @module model/Role
* @version 2.0.0
*/
export default class Role {
    /**
    * Constructs a new <code>Role</code>.
    * Representation of a Role, central container of permissions, actions and parameters.
    * @alias module:model/Role
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Role</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Role} obj Optional instance to populate.
    * @return {module:model/Role} The populated <code>Role</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Role();

            
            
            

            if (data.hasOwnProperty('ACL')) {
                obj['ACL'] = ApiClient.convertToType(data['ACL'], Object);
            }
            if (data.hasOwnProperty('MASKS')) {
                obj['MASKS'] = ApiClient.convertToType(data['MASKS'], Object);
            }
            if (data.hasOwnProperty('PARAMETERS')) {
                obj['PARAMETERS'] = ApiClient.convertToType(data['PARAMETERS'], Object);
            }
            if (data.hasOwnProperty('ACTIONS')) {
                obj['ACTIONS'] = ApiClient.convertToType(data['ACTIONS'], Object);
            }
            if (data.hasOwnProperty('APPLIES')) {
                obj['APPLIES'] = ApiClient.convertToType(data['APPLIES'], Object);
            }
        }
        return obj;
    }

    /**
    * Key/value associating workspace IDs and rights strings (r/w)
    * @member {Object} ACL
    */
    ACL = undefined;
    /**
    * Folders permissions masks
    * @member {Object} MASKS
    */
    MASKS = undefined;
    /**
    * Refined values of plugins parameters
    * @member {Object} PARAMETERS
    */
    PARAMETERS = undefined;
    /**
    * Enabled/disabled actions of plugins
    * @member {Object} ACTIONS
    */
    ACTIONS = undefined;
    /**
    * Set of profiles on which this role automatically applies
    * @member {Object} APPLIES
    */
    APPLIES = undefined;








}


