/**
 * Pydio API V2
 * Access to a Pydio Server. Second version of the API.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import TaskSchedule from './TaskSchedule';





/**
* The Task model module.
* @module model/Task
* @version 2.0.0
*/
export default class Task {
    /**
    * Constructs a new <code>Task</code>.
    * Background operation started on the server. It&#39;s the client mission to check it on a regular basis.
    * @alias module:model/Task
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Task</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Task} obj Optional instance to populate.
    * @return {module:model/Task} The populated <code>Task</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Task();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('wsId')) {
                obj['wsId'] = ApiClient.convertToType(data['wsId'], 'String');
            }
            if (data.hasOwnProperty('actionName')) {
                obj['actionName'] = ApiClient.convertToType(data['actionName'], 'String');
            }
            if (data.hasOwnProperty('schedule')) {
                obj['schedule'] = TaskSchedule.constructFromObject(data['schedule']);
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {Number} status
    */
    status = undefined;
    /**
    * @member {String} label
    */
    label = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {String} userId
    */
    userId = undefined;
    /**
    * @member {String} wsId
    */
    wsId = undefined;
    /**
    * @member {String} actionName
    */
    actionName = undefined;
    /**
    * @member {module:model/TaskSchedule} schedule
    */
    schedule = undefined;
    /**
    * @member {Object} parameters
    */
    parameters = undefined;








}


