/**
 * Pydio API V2
 * Access to a Pydio Server. Second version of the API.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PydioApiV2);
  }
}(this, function(expect, PydioApiV2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PydioApiV2.AdminWorkspace();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdminWorkspace', function() {
    it('should create an instance of AdminWorkspace', function() {
      // uncomment below and update the code to test AdminWorkspace
      //var instane = new PydioApiV2.AdminWorkspace();
      //expect(instance).to.be.a(PydioApiV2.AdminWorkspace);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new PydioApiV2.AdminWorkspace();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instane = new PydioApiV2.AdminWorkspace();
      //expect(instance).to.be();
    });

    it('should have the property display (base name: "display")', function() {
      // uncomment below and update the code to test the property display
      //var instane = new PydioApiV2.AdminWorkspace();
      //expect(instance).to.be();
    });

    it('should have the property displayStringId (base name: "displayStringId")', function() {
      // uncomment below and update the code to test the property displayStringId
      //var instane = new PydioApiV2.AdminWorkspace();
      //expect(instance).to.be();
    });

    it('should have the property accessType (base name: "accessType")', function() {
      // uncomment below and update the code to test the property accessType
      //var instane = new PydioApiV2.AdminWorkspace();
      //expect(instance).to.be();
    });

    it('should have the property writeable (base name: "writeable")', function() {
      // uncomment below and update the code to test the property writeable
      //var instane = new PydioApiV2.AdminWorkspace();
      //expect(instance).to.be();
    });

    it('should have the property isTemplate (base name: "isTemplate")', function() {
      // uncomment below and update the code to test the property isTemplate
      //var instane = new PydioApiV2.AdminWorkspace();
      //expect(instance).to.be();
    });

    it('should have the property groupPath (base name: "groupPath")', function() {
      // uncomment below and update the code to test the property groupPath
      //var instane = new PydioApiV2.AdminWorkspace();
      //expect(instance).to.be();
    });

    it('should have the property parameters (base name: "parameters")', function() {
      // uncomment below and update the code to test the property parameters
      //var instane = new PydioApiV2.AdminWorkspace();
      //expect(instance).to.be();
    });

    it('should have the property features (base name: "features")', function() {
      // uncomment below and update the code to test the property features
      //var instane = new PydioApiV2.AdminWorkspace();
      //expect(instance).to.be();
    });

    it('should have the property mask (base name: "mask")', function() {
      // uncomment below and update the code to test the property mask
      //var instane = new PydioApiV2.AdminWorkspace();
      //expect(instance).to.be();
    });

    it('should have the property info (base name: "info")', function() {
      // uncomment below and update the code to test the property info
      //var instane = new PydioApiV2.AdminWorkspace();
      //expect(instance).to.be();
    });

  });

}));
