/**
 * Pydio API V2
 * Access to a Pydio Server. Second version of the API.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PydioApiV2);
  }
}(this, function(expect, PydioApiV2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PydioApiV2.NodesDiff();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NodesDiff', function() {
    it('should create an instance of NodesDiff', function() {
      // uncomment below and update the code to test NodesDiff
      //var instane = new PydioApiV2.NodesDiff();
      //expect(instance).to.be.a(PydioApiV2.NodesDiff);
    });

    it('should have the property add (base name: "add")', function() {
      // uncomment below and update the code to test the property add
      //var instane = new PydioApiV2.NodesDiff();
      //expect(instance).to.be();
    });

    it('should have the property update (base name: "update")', function() {
      // uncomment below and update the code to test the property update
      //var instane = new PydioApiV2.NodesDiff();
      //expect(instance).to.be();
    });

    it('should have the property remove (base name: "remove")', function() {
      // uncomment below and update the code to test the property remove
      //var instane = new PydioApiV2.NodesDiff();
      //expect(instance).to.be();
    });

  });

}));
