/**
 * Pydio API V2
 * Access to a Pydio Server. Second version of the API.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PydioApiV2);
  }
}(this, function(expect, PydioApiV2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PydioApiV2.Role();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Role', function() {
    it('should create an instance of Role', function() {
      // uncomment below and update the code to test Role
      //var instane = new PydioApiV2.Role();
      //expect(instance).to.be.a(PydioApiV2.Role);
    });

    it('should have the property ACL (base name: "ACL")', function() {
      // uncomment below and update the code to test the property ACL
      //var instane = new PydioApiV2.Role();
      //expect(instance).to.be();
    });

    it('should have the property MASKS (base name: "MASKS")', function() {
      // uncomment below and update the code to test the property MASKS
      //var instane = new PydioApiV2.Role();
      //expect(instance).to.be();
    });

    it('should have the property PARAMETERS (base name: "PARAMETERS")', function() {
      // uncomment below and update the code to test the property PARAMETERS
      //var instane = new PydioApiV2.Role();
      //expect(instance).to.be();
    });

    it('should have the property ACTIONS (base name: "ACTIONS")', function() {
      // uncomment below and update the code to test the property ACTIONS
      //var instane = new PydioApiV2.Role();
      //expect(instance).to.be();
    });

    it('should have the property APPLIES (base name: "APPLIES")', function() {
      // uncomment below and update the code to test the property APPLIES
      //var instane = new PydioApiV2.Role();
      //expect(instance).to.be();
    });

  });

}));
